plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.moduflow'
    compileSdk {
        version = release(36)
    }

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.example.moduflow"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "AI_SERVER_HOST", '"moduflow-ai-489316272296.asia-northeast3.run.app"'
        buildConfigField "int",    "AI_SERVER_PORT", "443"
        buildConfigField "String", "API_SERVER_URL",  '"https://3-39-194-42.sslip.io/"'
        buildConfigField "String", "PWA_URL",         '"https://modu-flow-frontend.vercel.app"'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.androidx.browser
    implementation libs.androidx.webkit
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'org.altbeacon:android-beacon-library:2.19.5'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    implementation libs.androidx.camera.core
    implementation libs.androidx.camera.camera2
    implementation libs.androidx.camera.lifecycle
    implementation libs.androidx.camera.view

    // Networking & JSON
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'
    implementation 'com.google.code.gson:gson:2.10.1'

    // UI
    implementation 'com.google.android.material:material:1.10.0'
}
